### ISSUE TITLE
Support different level function references

### ISSUE THREAD

**Issue by elisalech** [andreypfau/intellij-ton#24]
Plugin does not support peeking to a definition of a different nesting level functions other than a level of a current file. Finding functions on the same level works fine.

Would be great to implement this feature.

Plugin version: 0.8.0

https://user-images.githubusercontent.com/31648261/167327526-4ae17d63-d267-4ae5-baf8-b35f80f3c982.mov

**Comment by andreypfau** [comment]
Try release candidate:
[intellij-ton-1.0.0-RC+2205211824.zip](https://github.com/andreypfau/intellij-ton/files/8748163/intellij-ton-1.0.0-RC%2B2205211824.zip)
